Update CI (#292)
- Allow publishing of Docker images of API / state manager separately
using tags e.g. "api@v2.1.0" -> "dragalia-api:2.1.0"
- Push to GitHub container registry instead of Docker Hub
- Use environments to show deployment status on main repository page

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -16,7 +16,8 @@ on:
         type: string
         description: Docker image name
       image-tag:
-        required: true
+        required: false
+        default: "undefined"
         type: string
         description: Docker image tag
 
@@ -31,22 +32,43 @@ jobs:
         dotnet-version: ["7.0.x"]
 
     steps:
+      - name: derive tag
+        id: derive-tag
+        run: |
+          TAG_REGEX="[\w]+?@v(.*)"
+          echo "Ref: ${{ inputs.ref }}"
+          echo "Tag: ${{ inputs.image-tag }}"
+          
+          if [ ${{ inputs.image-tag }} != "undefined" ]
+          then
+            echo "tag=${{ inputs.image-tag }}" >> "$GITHUB_OUTPUT"
+            exit 0;
+          fi
+          
+          if [ ${{ inputs.ref }} = "develop" ]
+          then
+             echo "tag=latest" >> "$GITHUB_OUTPUT"
+          elif [[ ${{ inputs.ref }} =~ $TAG_REGEX ]]
+          then
+             echo "tag=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
+          else
+            echo "No image-tag provided and failed to derive image tag from ref"
+            exit 1;
+          fi
+          
       - uses: actions/checkout@v3
         with:
           ref: ${{ inputs.ref }}
-      - uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+      - name: Log in to registry
+        # This is where you will update the personal access token to GITHUB_TOKEN
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
       - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: ${{ matrix.dotnet-version }}
-      - uses: docker/setup-buildx-action@v2
       - name: Build and push
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          file: ${{ inputs.dockerfile }}
-          push: true
-          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
+        run: |
+          IMAGE=ghcr.io/sapiensanatis/${{ inputs.image-name }}:${{ steps.derive-tag.outputs.tag }}
+          
+          docker build . --file ${{ inputs.dockerfile }} --tag ${IMAGE}
+          docker push ${IMAGE}
